name: CI

on: [push]

jobs:
    deploy:
        # if: ${{ false }} # Please delete this line
        env:
          HUGO_VERSION: ${{ github.sha }}
          TZ: Asia/Shanghai
        runs-on: ubuntu-latest
        
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                submodules: true
            
            - name: Set git config core.quotepath false # https://github.com/gohugoio/hugo/issues/9810#issuecomment-1107519804
              run: git config --global core.quotepath false
  
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '16.x'
                
            - name: Install Theme
              run: cd themes/hugo-theme-luna && yarn install --production
                
            - name: Install PostCSS-CLI
              run: npm install postcss-cli -g

            - name: Setup hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: '0.104.0'
                extended: true

            - name: Build Hugo
              run: echo "HUGO_VERSION -> $HUGO_VERSION" && hugo --gc --minify --cleanDestinationDir

            - name: Hugo-Encrypt
              run: cd themes/hugo-theme-luna && node ./hugo-encrypt.js

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY  }}
                # 获取提交文章源码时的commit message，作为发布gh-pages分支的信息
                commit_message: ${{ github.event.head_commit.message }}
                full_commit_message: ${{ github.event.head_commit.message }}
                github_token: ${{ secrets.GITHUB_TOKEN }}
                # GITHUB_TOKEN不是个人访问令牌，GitHub Actions 运行器会自动创建一个GITHUB_TOKEN密钥以在您的工作流程中进行身份验证。因此，您无需任何配置即可立即开始部​​署
                allow_empty_commit: true # 允许空提交

                personal_token: ${{ secrets.TOKEN }}
                external_repository: "ecnu-ica22/ecnu-ica22.github.io"
                publish_branch: main
                publish_dir: ./docs
                force_orphan: true
                user_name: ecnu-ica22
                user_email: ecnu_ica@163.com